In [51]:
import pandas as pd
import numpy as np

In [52]:
pd.__version__

'2.3.2'

In [53]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv

--2025-09-27 08:49:19--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 

185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 874188 (854K) [text/plain]
Saving to: ‘car_fuel_efficiency.csv.1’

car_fuel_efficiency 100%[===================>] 853.70K  1.64MB/s    in 0.5s    

2025-09-27 08:49:21 (1.64 MB/s) - ‘car_fuel_efficiency.csv.1’ saved [874188/874188]



In [54]:
df = pd.read_csv("car_fuel_efficiency.csv")
df.shape

(9704, 11)

In [55]:
df.fuel_type.unique()

array(['Gasoline', 'Diesel'], dtype=object)

In [56]:
df.isnull().any().sum()

np.int64(4)

In [57]:
df.loc[df.origin == "Asia", "fuel_efficiency_mpg"].max()

np.float64(23.759122836520497)

In [58]:
median_val = df.horsepower.median()
mode_val = df.horsepower.mode()
df["horsepower"] = df.horsepower.fillna(mode_val)
new_median_val = df.horsepower.median()

print(f"Old median: {median_val}, new median: {new_median_val}")

Old median: 149.0, new median: 149.0


In [59]:
df_asia_sample = df.loc[df.origin == "Asia", ["vehicle_weight", "model_year"]].head(7)
X = df_asia_sample.to_numpy()
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [60]:
XTX = X.T@X

In [61]:
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [62]:
XTX_inv = np.linalg.inv(XTX)

In [63]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [64]:
w = XTX_inv@X.T@y

In [65]:
w.sum()

np.float64(0.5187709081074016)